"use client";

/**
 * SIH26056 — Persistent data-mode indicator.
 *
 * Renders one of four labels, always, in a full-width bar directly beneath the
 * header:
 *
 *   LIVE DATA            collected from a real permitted source
 *   SIMULATED DATA       generated by the calibrated simulator
 *   OFFLINE PREVIEW      replayed from a checked-in fixture
 *   SOURCE UNAVAILABLE   no data exists / backend unreachable
 *
 * Deliberately NOT a tooltip, a badge in a corner, or a colour hint. The audit's
 * central finding was that synthetic figures were displayed with a "LIVE INDEX
 * STREAM" label, so the distinction has to be unavoidable rather than discoverable.
 *
 * The banner is never hidden. Even in LIVE mode it stays visible, because a reader
 * needs to be able to confirm the mode rather than infer it from the absence of a
 * warning.
 */

import { AlertTriangle, CheckCircle2, FlaskConical, WifiOff } from "lucide-react";
import { DATA_MODE } from "../lib/api";

const PRESENTATION = {
  [DATA_MODE.LIVE]: {
    tone: "live",
    Icon: CheckCircle2,
    detail:
      "Figures are computed from fare observations collected from a real permitted " +
      "source. They are provisional research output and are not official statistics.",
  },
  [DATA_MODE.SIMULATED]: {
    tone: "simulated",
    Icon: FlaskConical,
    detail:
      "Figures are computed by the real index engine from a calibrated fare " +
      "simulator. No airline or travel portal was contacted. They demonstrate that " +
      "the methodology computes correctly and say nothing about actual Indian " +
      "airfare inflation.",
  },
  [DATA_MODE.OFFLINE]: {
    tone: "offline",
    Icon: FlaskConical,
    detail:
      "Figures are computed from a checked-in fixture replayed for offline " +
      "demonstration. No source was contacted and these are not measurements.",
  },
  [DATA_MODE.UNAVAILABLE]: {
    tone: "unavailable",
    Icon: AlertTriangle,
    detail:
      "No index has been computed, so no figures are shown. Placeholder values are " +
      "deliberately not substituted.",
  },
  [DATA_MODE.DISCONNECTED]: {
    tone: "unavailable",
    Icon: WifiOff,
    detail:
      "The backend is unreachable, so no figures are available. Values render as " +
      "N/A rather than falling back to illustrative constants.",
  },
};

export default function DataModeBanner({ mode, reason, isPublishable, suppressionReason }) {
  const label = mode || DATA_MODE.DISCONNECTED;
  const presentation = PRESENTATION[label] || PRESENTATION[DATA_MODE.DISCONNECTED];
  const { tone, Icon, detail } = presentation;

  return (
    <div
      className={`data-mode-banner data-mode-${tone}`}
      role="status"
      aria-live="polite"
      data-testid="data-mode-banner"
      data-mode={label}
    >
      <div className="data-mode-inner">
        <span className="data-mode-label" data-testid="data-mode-label">
          <Icon size={15} aria-hidden="true" />
          {label}
        </span>
        <span className="data-mode-detail">
          {reason ? `${detail} ${reason}` : detail}
        </span>
      </div>

      {isPublishable === false && (
        <div className="data-mode-suppression" data-testid="data-mode-suppression">
          <AlertTriangle size={14} aria-hidden="true" />
          <span>
            <strong>Figure marked not publishable.</strong>{" "}
            {suppressionReason ||
              "Basket coverage is below the minimum required to publish a national figure."}
          </span>
        </div>
      )}
    </div>
  );
}

/**
 * Compact inline variant, for use inside a panel that displays figures away from the
 * top-level banner. Same vocabulary, so a reader never has to reconcile two labels.
 */
export function DataModeChip({ mode, className = "" }) {
  const label = mode || DATA_MODE.DISCONNECTED;
  const { tone } = PRESENTATION[label] || PRESENTATION[DATA_MODE.DISCONNECTED];
  return (
    <span
      className={`data-mode-chip data-mode-chip-${tone} ${className}`.trim()}
      data-testid="data-mode-chip"
      data-mode={label}
    >
      {label}
    </span>
  );
}
